
POST http://127.0.0.1:8000/api/ajouterfichier

Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="bacemayadi.jpg"

< ./bacemayadi.jpg
--WebAppBoundary--

